nats:
  host: nats:4222
  allow_reconnect: true
  max_reconnect_attempts: 5
  reconnect_wait: 5s
  timeout: 1s

queue:
  topic: crawler
  group: crawlers

monitor:
  topic: monitoring

database:
  host: database
  port: 5432
  database: crawler
  username: ct-user
  password: ct-pass
  ssl_mode: disable
  migrate: false

crawler:
  use_api: true