version: "3.5"

services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
    networks: ["ctNet"]

  chrome:
    image: zenika/alpine-chrome:latest
    command: [ chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
    networks: ["ctNet"]

  database:
    image: 'postgres:latest'
    container_name: database
    ports:
      - "5444:5432"
    networks: ["ctNet"]
    environment:
      POSTGRES_USER: "ct-user"
      POSTGRES_PASSWORD: "ct-pass"
      POSTGRES_DB: "crawler"
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
      - ./docs/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  crawler:
    build:
      context: "./"
      dockerfile: ./crawler/Dockerfile
    links:
      - nats
      - database
      - chrome
    depends_on:
      - nats
      - database
      - chrome
    networks: ["ctNet"]
    restart: on-failure

  listener:
    container_name: listener
    build:
      context: "./"
      dockerfile: ./listener/Dockerfile
    ports:
      - "7777:7777"
    links:
      - nats
    depends_on:
      - nats
      - crawler
    networks: ["ctNet"]
    restart: on-failure

  reader:
    container_name: reader
    build:
      context: "./"
      dockerfile: ./reader/Dockerfile
    depends_on:
      - listener
    networks: ["ctNet"]

networks:
  ctNet:
    name: ctNet

volumes:
  database:
    driver: local