grpc:
  listener_address: listener:7777
  dial_timeout: 1s
  request_timeout: 100ms
  ping_interval: 10s
  ping_timeout: 1s

general:
  skip_rows: 1
  buffer_size: 0
  url_domain: https://channelstore.roku.com